---
title: "Untitled"
author: "Lulu Zhang"
date: "November 30, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
backup=data
data = backup
data = read.csv("MyLA311_Service_Request_Data_2016.csv")
library(dplyr)
library(ggplot2)
library(ggmap)
library(lubridate)
```


Distribution of Services
```{r}
service_type = data %>%
  filter(Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarise(frequency= n())

data$CreatedDate=mdy_hms(data$CreatedDate)
data$UpdatedDate=mdy_hms(data$UpdatedDate)
data$ProcessDate = difftime(data$UpdatedDate,data$CreatedDate,units = c("hours"))


process_time = data %>%
  filter(ActionTaken == "SR Created"& Status =="Closed") %>%
  group_by(RequestType)%>%
  summarise(avg = mean(ProcessDate))
  
service_type$top3 = service_type$frequency > 70000

  
p1 = ggplot(service_type,aes(x=reorder(RequestType, -frequency), y= frequency/1000, fill =service_type$top3)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(limits = c(0,540),
    labels = seq(0,540,100),
                     breaks = seq(0,540,100)) +
  ylab("Frequency") +
  geom_text(aes(label = frequency/1000), vjust = -0.2) +
  scale_fill_manual(values = c("cornflowerblue","indianred1"), guide =F)+
  theme(axis.text.x=element_text(angle = 30,vjust = 1, hjust=1))+
  xlab("")


lev =levels(process_time$RequestType)
lev=lev[c(1,5,8,7,3,2,12,6,10,9,11,4)]
process_time$RequestType=factor(process_time$RequestType, levels =lev)


 p2 =  ggplot(process_time,aes(x = RequestType, y = avg,group = 1))+
  geom_line() +
  geom_text(aes(label = as.integer(avg)),hjust =-0.6,vjust=0.9)+
  theme(axis.text.x=element_blank())+
  ylab("Average Processing Time (hours)")+
   xlab("") +
   geom_point(size =1)

library(gridExtra)
grid.arrange(p2,p1, nrow = 2,
             top = "Services Type Frequency(thousands) vs. Processing Time(hours)") 


```


Distribution of Departments
```{r}
depart = data1 %>%
  filter(Status !="Cancelled" & Owner !="BOE") %>%
  droplevels()%>%
  group_by(Owner) %>%
  summarise(count = n())

depart$top3 = depart$count > 20000

p3 = ggplot(data= depart,aes(x= reorder(Owner,-count), y =count/1000, fill = top3)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(limits = c(0,770),
                     labels = seq(0,770,100),
                     breaks = seq(0,770,100)) +
  xlab("") +
  ylab("Frequency") +
  geom_text(aes(label = count/1000), vjust = -0.2) +
  scale_fill_manual(values = c("cornflowerblue","indianred1"), guide =F)


data1= data %>% filter(Owner !="")

depart_time = data1 %>%
  filter(ActionTaken == "SR Created"& Status =="Closed") %>%
  droplevels()%>%
  group_by(Owner)%>%
  summarise(avg = mean(ProcessDate))


depart_time$Owner=factor(depart_time$Owner, levels =c("BOS","OCB","BSL","ITA","BSS","LADWP"))


p4 = 
  ggplot(depart_time,aes(x = Owner, y = avg,group=1))+
  geom_line()+
  theme(axis.text.x=element_text())+
  geom_text(aes(label = as.integer(avg)),hjust =-0.6,vjust=0.9)+
  ylab("Average Processing Time (hours)")+
  xlab("")+
  geom_point(size=1,shape=3)


grid.arrange(p4,p3, nrow = 2,
             top = "Department Frequency(thousands) vs. Processing Time(hours)") 


```



App vs Phone call referrals, service type question for each input channel
```{r}
input_channel = data %>%
  filter(Status !="Cancelled") %>%
  group_by( RequestSource) %>%
  summarize(frequency = n())

ggplot(input_channel, aes(x= RequestSource, y = frequency/1000))+
  geom_bar(stat = "identity") +
  coord_flip()+
  geom_text(aes(label=frequency),hjust = -0.1)

data %>%
  filter(Status !="Cancelled") %>%
  group_by(RequestType, RequestSource) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency)) +
  geom_bar(stat ="identity") +
  facet_wrap((~RequestSource))


data %>%
  filter(RequestSource == "Call" & Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency/1000)) +
  geom_bar(stat ="identity")+
  coord_flip()+
  ggtitle("Services Requested by Call")

data %>%
  filter(RequestSource == "Driver Self Report" & Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency/1000)) +
  geom_bar(stat ="identity")+
  coord_flip()+
  ggtitle("Services Requested by Driver Self Report")

data %>%
  filter(RequestSource == "Mobile App" & Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency/1000)) +
  geom_bar(stat ="identity")+
  coord_flip()+
  ggtitle("Services Requested by Mobile App")


data %>%
  filter(RequestSource == "Self Service" & Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency/1000)) +
  geom_bar(stat ="identity")+
  coord_flip()+
  ggtitle("Services Requested by Self Service")


data %>%
  filter(RequestSource == "Email" & Status !="Cancelled") %>%
  group_by(RequestType) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x= RequestType,y= frequency/1000)) +
  geom_bar(stat ="identity")+
  coord_flip()+
  ggtitle("Services Requested by Email")


subset1 =data %>% 
   filter(RequestType %in% 
            c("Bulky Items",
              "Metal/Household Appliances",
              "Illegal Dumping Pickup",
              "Single Streetlight Issue",
              "Graffiti Removal") &
          RequestSource %in% 
            c("Call",
              "Email",
              "Driver Self Report",
              "Self Service",
              "Mobile App") &
          Status != "Cancelled") %>%
  group_by(RequestType,RequestSource) %>%
  summarize(frequency=n())

ggplot(subset1, aes(x= RequestType, y = frequency/1000, fill = RequestSource))+
  geom_bar(position = position_dodge(0.9), stat = "Identity") +
  ggtitle("TOP5 Seriveces by Top5 Input Channel")+
  theme_light()






```



Timeframe distribution
```{r}

data$CreatedDate = mdy_hms(data$CreatedDate)

subset2 = data %>%
  group_by(RequestType, month = month(CreatedDate, label = T)) %>%
  summarise(count = n())

ggplot(data = subset2, aes(x = month, y = count, group =1)) +
  geom_line(stat = "identity") +
  facet_wrap(~RequestType,nrow = 4)


subset2 %>%
ggplot(aes(x = month, y = count/1000, group = RequestType, col=RequestType)) +
  geom_line(stat = "identity") +
  ggtitle("All Services Request by Month")


subset2 %>%
  filter(RequestType != "Bulky Items" & RequestType != "Graffiti Removal") %>%
ggplot(aes(x = month, y = count, group = RequestType, col=RequestType)) +
  geom_line(stat = "identity") +
  ggtitle("Services Request by Month (no Bulky Items & Graffiti Removal)")


subset2 %>%
  filter(RequestType != "Bulky Items" & RequestType != "Graffiti Removal"& RequestType != "Illegal Dumping Pickup"& RequestType != "Metal/Household Appliances"& RequestType != "Electronic Waste"& RequestType != "Dead Animal Removal") %>%
ggplot(aes(x = month, y = count, group = RequestType, col=RequestType)) +
  geom_line(stat = "identity") +
  ggtitle("Services Request by Month (count <2200)")


subset2 %>%
  filter(RequestType =="Bulky Items") %>%
  ggplot(aes(x = month, y = count, group =1)) +
  geom_line(stat = "identity") +
  ggtitle("Bulky Items Service Request by Month")
  

  ggplot(subset2, aes(x=month, y = RequestType, fill = count))+
  geom_tile() +
  scale_fill_gradient(low = "white", high = "darkgreen") +
  ylab("hour of the day") +
  xlab("day of the week")


```
process time
average processing time group by requesttype
```{r}
str(data$UpdatedDate)
data$CreatedDate=mdy_hms(data$CreatedDate)
data$UpdatedDate=mdy_hms(data$UpdatedDate)
data$ProcessDate = difftime(data$UpdatedDate,data$CreatedDate,units = c("hours"))
data$ProcessDate=as.integer(data$ProcessDate)

data %>%
  filter(ActionTaken == "SR Created"& Status =="Closed") %>%
  group_by(RequestType)%>%
  summarise(avg = mean(ProcessDate)) %>%
  ggplot(aes(x = RequestType, y = avg,fill= avg >200))+
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("lightblue","red"), guide =F)+
  geom_text(aes(label = as.integer(avg)),hjust =0.6,)+
  theme(axis.text.x=element_text(angle = 45,vjust = 1, hjust=1))+
  ylab("Average Processing Time (hours)")+
  ggtitle("")
```

average processing time group by owner

```{r}
data %>%
  filter(ActionTaken == "SR Created"& Status =="Closed") %>%
  group_by(Owner)%>%
  summarise(avg = mean(ProcessDate)) %>%
  ggplot(aes(x = Owner, y = avg))+
  geom_bar(stat = "identity")+
  theme(axis.text.x=element_text(angle = 45,vjust = 1, hjust=1))+
  geom_text(aes(label = as.integer(avg)),hjust =0.6,)+
  ylab("Average Processing Time (hours)")+
  ggtitle("")
```
overall call map
```{r}
LA = qmap("Los Angeles", zoom = 14, maptype = "roadmap", color="bw")
LA +
  stat_density2d(data = subset(data,data$Latitude != ""),
                 aes(x = Longitude, y = Latitude , fill = ..level..),
                 geom = "polygon", alpha = 0.2)+
  scale_fill_gradient(low = "white", high = "darkred" )
```


```{r}
data_finished=data %>%
  filter(ActionTaken == "SR Created"& Status =="Closed")
LA +
  stat_density2d(data = subset(data_finished,data_finished$Latitude != ""),
                 aes(x = Longitude, y = Latitude , fill = ..level..),
                 geom = "polygon", alpha = 0.2)+
  scale_fill_gradient(low = "white", high = "darkred" )
```


```{r}
data %>%
  filter(Status=="Cancelled"& RequestType=="Other") %>%
ggplot(aes(x = Longitude, y = Latitude)) +
  geom_point() +
  geom_text(aes(label = RequestType), vjust = -1) +
  coord_map() 
  



```

